version: '2.2'
services:
  notification-service:
    build: notification-service
    container_name: pm-notification-service
    privileged: true
    # mem_limit: 400m
    # mem_reservation: 300m
    cpu_count: 1
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8000:8000
    networks:
    - pm-net
