spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

logging:
  config: '/var/piggymetrics/logback-spring.xml'
  file: '/var/log/piggymetrics/app.log'

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
