version: '2.2'
services:
  registry:
    volumes:
    - ./etc/logback-spring.xml:/var/piggymetrics/logback-spring.xml
    - registry-log:/var/log/piggymetrics

  registry-filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    privileged: true
    restart: always
    volumes:
    - ./registry/filebeat.yml:/usr/share/filebeat/filebeat.yml
    - registry-log:/var/log/piggymetrics
    links:
    - elasticsearch
    networks:
      - pm-net
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  registry-log:
