version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: pm-es7
    privileged: true
    environment:
      discovery.type: single-node
    restart: always
    ports:
    - 9200:9200
    networks:
      - pm-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: pm-kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - pm-net
