version: '2.2'
services:
  elasticsearch:
    # image: elasticsearch:7.10.1
    build: elastic-stack
    container_name: pm-es7
    privileged: true
    environment:
      discovery.type: single-node
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9200/", "||", "exit", "1"]
    #   interval: 30s
    #   timeout: 30s
    restart: always
    ports:
    - 9200:9200
    networks:
      - pm-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: pm-kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - pm-net
    depends_on:
      elasticsearch:
        condition: service_healthy
