## TODO: use elastic-ecs logging

# regxp partten https://www.elastic.co/guide/en/beats/filebeat/current/regexp-support.html
# java stack example  https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
# log rotation https://www.elastic.co/guide/en/beats/filebeat/current/file-log-rotation.html
filebeat.inputs:
- type: log
  paths: /var/log/piggymetrics.log.json*
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true

  fields:
    app-name: 'piggymetrics'

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
  - index: 'piggymetrics-%{+yyyy.MM.dd}'
    when.equals:
      fields:
        app-name: 'piggymetrics'

setup.kibana.host: "http://kibana:5601"
setup.ilm.enabled: false

# setup.template.name: "piggymetrics"
# setup.template.pattern: "*-service"
# setup.template.enabled: false
