## TODO: use elastic-ecs logging

# regxp partten https://www.elastic.co/guide/en/beats/filebeat/current/regexp-support.html
# java stack example  https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
# log rotation https://www.elastic.co/guide/en/beats/filebeat/current/file-log-rotation.html
filebeat.inputs:
- type: log
  - "/var/log/piggymetrics/config-service/service.log*"
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
# TODO： annotation or field
  fields:
   service-name: 'config'

  - "/var/log/piggymetrics/config-service/gc.log*"
# TODO： annotation or field
  fields:
   service-name: 'config'
   log-type: gc

  - "/var/log/piggymetrics/registry-service/service.log*"
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
# TODO： annotation or field
  fields:
   service-name: 'registry'

  - "/var/log/piggymetrics/registry-service/gc.log*"
# TODO： annotation or field
  fields:
   service-name: 'registry'
   log-type: gc


  - "/var/log/piggymetrics/gateway/service.log*"
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
# TODO： annotation or field
  fields:
   service-name: 'gateway'

  - "/var/log/piggymetrics/gateway/gc.log*"
# TODO： annotation or field
  fields:
   service-name: 'gateway'
   log-type: gc

  - "/var/log/piggymetrics/auth-service/service.log*"
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
# TODO： annotation or field
  fields:
   service-name: 'auth'

  - "/var/log/piggymetrics/auth-service/gc.log*"
# TODO： annotation or field
  fields:
   service-name: 'auth'
   log-type: gc

  - "/var/log/piggymetrics/account-service/service.log*"
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
# TODO： annotation or field
  fields:
   service-name: 'account'

  - "/var/log/piggymetrics/account-service/gc.log*"
# TODO： annotation or field
  fields:
   service-name: 'account'
   log-type: gc

  - "/var/log/piggymetrics/notification-service/service.log*"
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
# TODO： annotation or field
  fields:
   service-name: 'notification'

  - "/var/log/piggymetrics/notification-service/gc.log*"
# TODO： annotation or field
  fields:
   service-name: 'notification'
   log-type: gc

  - "/var/log/piggymetrics/statistics-service/service.log*"
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
# TODO： annotation or field
  fields:
   service-name: 'statistics'

  - "/var/log/piggymetrics/statistics-service/gc.log*"
# TODO： annotation or field
  fields:
   service-name: 'statistics'
   log-type: gc

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
  - index: 'piggymetrics-service%{+yyyy.MM.dd}'
    when.equals:
      fields:
        app-name: 'piggymetrics'

  - index: 'piggymetrics-gc%{+yyyy.MM.dd}'
    when.equals:
      fields.log-type: 'gc'

setup.kibana.host: "http://kibana:5601"
setup.ilm.enabled: false

# setup.template.name: "piggymetrics"
# setup.template.pattern: "*-service"
# setup.template.enabled: false
