version: '2.2'
services:
  monitoring:
    volumes:
    - ./etc/logback-spring.xml:/var/piggymetrics/logback-spring.xml
    - monitoring-log:/var/log/piggymetrics

  monitoring-filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    privileged: true
    restart: always
    volumes:
    - ./monitoring/filebeat.yml:/usr/share/filebeat/filebeat.yml
    - monitoring-log:/var/log/piggymetrics
    links:
    - elasticsearch
    networks:
      - pm-net
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  monitoring-log:
