spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000

logging:
  config: 'etc/logback-spring.xml'
