version: '2.2'
services:
  turbine-stream-service:
    volumes:
    - ./etc/logback-spring.xml:/var/piggymetrics/logback-spring.xml
    - turbine-stream-service-log:/var/log/piggymetrics

  turbine-stream-service-filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    privileged: true
    restart: always
    volumes:
    - ./turbine-stream-service/filebeat.yml:/usr/share/filebeat/filebeat.yml
    - turbine-stream-service-log:/var/log/piggymetrics
    links:
    - elasticsearch
    networks:
      - pm-net
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  turbine-stream-service-log:
