version: '2.2'
services:
  turbine-stream-service:
    build: turbine-stream-service
    container_name: pm-turbine-stream-service
    privileged: true
    # mem_limit: 400m
    # mem_reservation: 300m
    cpu_count: 1
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    volumes:
    - ./etc/logback-spring.xml:/var/piggymetrics/logback-spring.xml
    restart: always
    depends_on:
      config:
        condition: service_healthy
    networks:
    - pm-net
